/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuM;

import clases.generadoras.Movil;
import excepciones.personalizadas.MovilNoEncontradoExeption;
import excepciones.personalizadas.VerficarCampoVacioException;
import javax.swing.JOptionPane;
import sistema_de_asistencia_medica.GestionHospital;

/**
 *
 * @author Raul
 */
public class BajaM extends javax.swing.JFrame {

    GestionHospital bajaMovil;
    Movil eliminarMovil;
    
    public BajaM(GestionHospital gh) {
        initComponents();
        bajaMovil = gh;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        busquedaAuto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mostrarMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mostrarModelo = new javax.swing.JTextField();
        BotonBuscarAuto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BotonEliminarAuto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("INGRESAR EL NUMERO DE PATENTE DEL VEHICULO");

        jLabel2.setText("MARCA");

        jLabel3.setText("MODELO");

        BotonBuscarAuto.setText("BUSCAR");
        BotonBuscarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarAutoActionPerformed(evt);
            }
        });

        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BotonEliminarAuto.setText("ELIMINAR");
        BotonEliminarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(BotonEliminarAuto))
                            .addComponent(busquedaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(BotonBuscarAuto))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busquedaAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarAuto))
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(BotonEliminarAuto))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarAutoActionPerformed
        try{
        bajaMovil.verificarCampoDNI(busquedaAuto.getText()); 
        
        eliminarMovil = bajaMovil.buscarMovil(busquedaAuto.getText());
        
        
            mostrarMarca.setText(eliminarMovil.getMarca());
            mostrarModelo.setText(eliminarMovil.getModelo());
        
        }catch(VerficarCampoVacioException cav){
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos obligatorios ", "Atencion!", JOptionPane.QUESTION_MESSAGE);
        }catch (MovilNoEncontradoExeption ex) {
             JOptionPane.showMessageDialog(this," No se ha encontrado el Movil" , "Error", JOptionPane.ERROR_MESSAGE);
        }catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, " NO HAY NINGUN MOVIL EN EL SISTEMA", "Atencion!", JOptionPane.QUESTION_MESSAGE);
}
    }//GEN-LAST:event_BotonBuscarAutoActionPerformed

    private void BotonEliminarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarAutoActionPerformed
        if(eliminarMovil!= null){
           bajaMovil.bajaMovil(eliminarMovil);
           JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
           this.mostrarMarca.setText("");
           this.mostrarModelo.setText("");
           
        }
        else{
            JOptionPane.showMessageDialog(this," no se pudo eliminar" , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonEliminarAutoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void busquedaAutoKeyTyped(java.awt.event.KeyEvent evt) {                                      
     char C= evt.getKeyChar();
     
     if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "Ingrese solo letras o numeros (AAA111)","Error", JOptionPane.ERROR_MESSAGE);
         busquedaAuto.setCursor(null);
     }
     else if(busquedaAuto.getText().length() >= 6){
         evt.consume();
         getToolkit().beep();
         JOptionPane.showMessageDialog(this, "Longitud maxima de seis caracteres","Error", JOptionPane.ERROR_MESSAGE);
         
     }
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscarAuto;
    private javax.swing.JButton BotonEliminarAuto;
    private javax.swing.JTextField busquedaAuto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mostrarMarca;
    private javax.swing.JTextField mostrarModelo;
    // End of variables declaration//GEN-END:variables
}
